plan_id: policy/product_team_a/product_x_user_data_retention
title: Wipeout Plan for User Data of Product X
description: This is an example wipeout plan.
scope: Product X
data_type: User data
identifier: Customer ID
deletion_timeline:
  - stage:
      action: Deletion
      purpose: User Health Data
      trigger:
        trigger_event: User-initiated deletion
        delay: 356 days
  - stage:
      action: Deletion
      purpose: Spam and Abuse
      trigger:
        trigger_event: Identifier expiration
        delay: 356 days