name: 'mapping-data-validation'

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}-mapping-data-validation'
  cancel-in-progress: true

jobs:
  snapshot:
    uses: 'abcxyz/pmap/.github/workflows/resource-mapping-check.yml@v0.0.5-rc' # Change here to pin the tag or commit.
    with:
      resource_mapping_directory: 'example/org/mapping' #Change here if you change the folder to store the mappings.
      go_version: '>=1.20.0'
